version: '3.9'
services:
  postgresql:
    container_name: postgres-task-list
    image: postgres:15.2-alpine3.17
    ports:
      - "5500:5432"
    restart: unless-stopped
    networks:
      - task-list
    environment:
      POSTGRES_DB: task-list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  task-list:
    driver: bridge